"""Validate the planned API and export the actual API and a readable draft reference."""

import argparse
import json
import re
from pathlib import Path

import yaml
from agenticiot.main import create_app
from openapi_spec_validator import validate

ROOT = Path(__file__).resolve().parents[1]


def outputs() -> dict[Path, str]:
    draft = yaml.safe_load((ROOT / "api/openapi.yaml").read_text())
    validate(draft)
    actual = create_app().openapi()
    validate(actual)
    lines = [
        "# Capability API — draft reference",
        "",
        "> Generated by `uv run python scripts/contracts.py`. Do not edit manually.",
        "> Design contract status. Execution supports virtual and MQTT-demo lights only.",
        "> Fresh reads and body-supplied context are unsupported.",
        "> See docs/api/node-local-services.md for implemented authorization and streaming.",
        "> Implemented endpoints are in `api/platform.openapi.json` and runtime `/docs`.",
        "",
        "Base path: `/v1`",
        "",
        "| Method | Path | Purpose | Status |",
        "|---|---|---|---|",
    ]
    implemented = {
        (re.sub(r"\{[^}]+\}", "{}", path), method)
        for path, operations in actual["paths"].items()
        for method in operations
    }
    for path, operations in draft["paths"].items():
        for method, operation in operations.items():
            if method not in {"get", "post", "put", "patch", "delete", "head", "options"}:
                continue
            summary = operation.get("summary", "").replace("|", "\\|")
            actual_path = re.sub(r"\{[^}]+\}", "{}", f"/v1{path}")
            status = "Implemented" if (actual_path, method) in implemented else "Planned"
            lines.append(f"| {method.upper()} | `{path}` | {summary} | {status} |")
    lines += ["", "## Schemas", ""]
    for name, schema in draft["components"]["schemas"].items():
        lines += [f"### {name}", "", "```json", json.dumps(schema, indent=2), "```", ""]
    return {
        ROOT / "api/platform.openapi.json": json.dumps(actual, indent=2, sort_keys=True) + "\n",
        ROOT / "docs/api/capability-reference.md": "\n".join(lines),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for path, content in outputs().items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                raise SystemExit(f"Contract artifact out of date: {path.relative_to(ROOT)}")
        else:
            path.write_text(content)
    print("Planned and implemented OpenAPI schemas validated; generated artifacts are current.")


if __name__ == "__main__":
    main()
